MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040
# ALLOW_WARNINGS = yes
# PICO_INTRINSICS_ENABLED = no

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = adns9800

VIA_ENABLE = yes

NKRO_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
LTO_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
CAPS_WORD_ENABLE = no
REPEAT_KEY_ENABLE = no
AUTO_SHIFT_ENABLE = no
QMK_SETTINGS = no
DYNAMIC_KEYMAP_ENABLE = no
